### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by BobbyTowers** [HelloWorld017/EconomyPotionShop#2]
Can you please update to 0.14.0?

**Comment by HelloWorld017** [comment]
I am too sorry to say that I can't because I'm a student and I have no time T_T

**Comment by BobbyTowers** [comment]
Never Mind, I just bumped the api and it works fine.

**Comment by BobbyTowers** [comment]
Now it doesn't work with the latest version of EconomyS

**Comment by Bidou0418** [comment]
please update the download with api 2.0

**Comment by HelloWorld017** [comment]
This plugin is out of date and I have no plans to update this plugin.
